function resolveRouteNodeLocation(routeName, index, routeNames, segments, { allowCrossings = true } = {}) {
	const normalizedName = normalizeLocationSearchName(routeName);
	const directLocation = locationData.find((location) => location.name === routeName)
		|| locationData.find((location) => normalizeLocationSearchName(location.name) === normalizedName)
		|| findLocationMarkerByName(routeName)?.location
		|| null;
	if (directLocation && (allowCrossings || !isCrossingLocation(directLocation))) {
		return directLocation;
	}

	const candidateCoordinates = [];
	const previousSegment = segments[index - 1];
	const nextSegment = segments[index];
	const previousEnd = previousSegment?.geometry?.coordinates?.[previousSegment.geometry.coordinates.length - 1];
	const nextStart = nextSegment?.geometry?.coordinates?.[0];
	if (previousEnd) {
		candidateCoordinates.push(previousEnd);
	}
	if (nextStart) {
		candidateCoordinates.push(nextStart);
	}

	for (const coordinate of candidateCoordinates) {
		const location = getLocationAtPathEndpoint(coordinate);
		if (location && (allowCrossings || !isCrossingLocation(location))) {
			return location;
		}
	}

	return null;
}

function getRouteNodeDisplayName(routeName, index, routeNames, segments, options = {}) {
	const allowCrossings = options.allowCrossings !== false;
	const normalizedRouteName = normalizeNodeName(routeName);
	if (!allowCrossings && normalizedRouteName === "Kreuzung") {
		return "Markierung";
	}

	const location = resolveRouteNodeLocation(routeName, index, routeNames, segments, options);
	if (location) {
		return isCrossingLocation(location) ? normalizeNodeName(location.name) : location.name;
	}

	return normalizedRouteName;
}

function getRoutePathDisplayName(segment) {
	return String(segment?.properties?.display_name || segment?.properties?.original_name || segment?.properties?.name || "").trim();
}

function escapeRouteDisplayRegex(value) {
	return String(value || "").replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function shouldShowRoutePathDisplayName(segment) {
	const displayName = getRoutePathDisplayName(segment);
	if (!displayName) {
		return false;
	}

	const subtype = normalizePathSubtype(segment?.properties?.feature_subtype || segment?.properties?.name);
	const autogeneratedPattern = new RegExp(`^${escapeRouteDisplayRegex(subtype)}-\\d+$`);
	return !autogeneratedPattern.test(displayName);
}
