CREATE TABLE IF NOT EXISTS location_reports (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    status VARCHAR(20) NOT NULL DEFAULT 'neu',
    name VARCHAR(80) NOT NULL,
    size VARCHAR(20) NOT NULL,
    lat DECIMAL(7, 3) NOT NULL,
    lng DECIMAL(7, 3) NOT NULL,
    source VARCHAR(200) NOT NULL,
    wiki_url VARCHAR(300) NULL,
    comment TEXT NULL,
    page_url VARCHAR(500) NULL,
    client_version VARCHAR(80) NULL,
    review_note TEXT NULL,
    reviewed_at DATETIME(3) NULL,
    request_origin VARCHAR(255) NULL,
    remote_ip VARCHAR(64) NULL,
    user_agent VARCHAR(500) NULL,
    PRIMARY KEY (id),
    KEY idx_location_reports_status_created_at (status, created_at),
    KEY idx_location_reports_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
